ferus_previs:
    pattern: /
    defaults: { _controller: FerusEventBundle:Previs:index }

ferus_previs_new:
    pattern: /new
    defaults: { _controller: FerusEventBundle:Previs:new }

ferus_previs_show:
    pattern: /{id}
    defaults: { _controller: FerusEventBundle:Previs:show }
    requirements:
        id: \d+

ferus_previs_edit:
    pattern: /{id}/edit
    defaults: { _controller: FerusEventBundle:Previs:edit }
    requirements:
        id: \d+

ferus_previs_remove:
     pattern: /{id}/remove
     defaults: { _controller: FerusEventBundle:Previs:remove }
     requirements:
         id: \d+

ferus_previs_calcul:
    pattern: /{id}/liste-courses
    defaults: { _controller: FerusEventBundle:Previs:calcul }
    requirements:
        id: \d+

ferus_previs_pdf:
    pattern: /{id}/download-pdf
    defaults: { _controller: FerusEventBundle:Previs:downloadPDF }
    requirements:
        id: \d+

ferus_previs_self_mail:
    pattern: /{id}/self-mail
    defaults: { _controller: FerusEventBundle:Previs:selfMail }
    requirements:
        id: \d+

ferus_previs_all_mail:
    pattern: /{id}/all-mail
    defaults: { _controller: FerusEventBundle:Previs:allMail }
    requirements:
            id: \d+
