parameters:
#    ferus_user.example.class: Ferus\UserBundle\Example

services:
#    ferus_user.example:
#        class: %ferus_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
