ferus_product_admin:
    path: /
    defaults:
        _controller: FerusProductBundle:Admin:index

ferus_product_admin_historical:
    path: /historical
    defaults:
        _controller: FerusProductBundle:Admin:historical

ferus_product_admin_historical_user:
    path: /historical/{id}
    defaults:
        _controller: FerusProductBundle:Admin:historical
    requirements:
        id: \d+

ferus_product_admin_list:
    path: /list
    defaults:
        _controller: FerusProductBundle:Admin:list
