ferus_categories:
    pattern:  /
    defaults: { _controller: FerusProductBundle:Category:index }

ferus_categories_new:
    pattern:  /new
    defaults: { _controller: FerusProductBundle:Category:new }