ferus_places:
    pattern:  /
    defaults: { _controller: FerusProductBundle:Place:index }

ferus_places_new:
    pattern:  /new
    defaults: { _controller: FerusProductBundle:Place:new }

ferus_places_show:
    pattern:  /{id}
    defaults: { _controller: FerusProductBundle:Place:show }
    requirements:
        id: \d+