ferus_stock_add:
    pattern:  /add
    defaults: { _controller: FerusProductBundle:Stock:add }

ferus_stock_move:
    pattern:  /move
    defaults: { _controller: FerusProductBundle:Stock:move }

ferus_stock_remove:
    pattern:  /remove
    defaults: { _controller: FerusProductBundle:Stock:remove }