<?php

namespace Ferus\EventBundle\Repository;

/**
 * BarProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarProductRepository extends \Doctrine\ORM\EntityRepository
{
}
