ferus_ProductBundle_category:
    resource: "@FerusProductBundle/Resources/config/routing/category.yml"
    prefix:   /categories

ferus_ProductBundle_product:
    resource: "@FerusProductBundle/Resources/config/routing/product.yml"
    prefix:   /