parameters:
#    ferus_product.example.class: Ferus\ProductBundle\Example

services:
#    ferus_product.example:
#        class: %ferus_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
