<?php

namespace Ferus\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Ferus\UserBundle\Entity\User;

/**
 * HistoricalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalRepository extends EntityRepository
{
    public function getHistoricalByUser(User $user = null)
    {
        $qb = $this->createQueryBuilder('h')
            ->leftJoin('h.author', 'u')
            ->addSelect('u');

        if (null !== $user) {
            $qb
                ->where('u.id = :user')
                ->setParameter('user', $user->getId());
        }

        $qb
            ->orderBy('h.date', 'DESC')
            ->getQuery()
        ;

        return $qb;
    }
}
